Repository GovReady/govready-q, pull requests merged in 2019-04, with the labels that each got.

#571 add a module spec validation rule that impute conditions must have a …
  guidedmodules/validate_module_specification.py
Labels: better, bug

#586 Fix 585
  guidedmodules/models.py
Labels: better

#616 Remove stray docs/source file
  docs/source/DatabaseStructure.md
Labels: documentation

#619 Improve docs for code scanning
  docs/source/Test.md
Labels: documentation

#618 Fix documentation problems in v0.8.6
  docs/source/Apps.md
  docs/source/Schema.md
Labels: priority
