Repository GovReady/govready-q, pull requests merged in 2021-01, with the labels that each got.

#1284 Fixes to 0.9.1.49 after merge.
  CHANGELOG.md
  VERSION
  controls/tests.py
  discussion/tests.py
  templates/controls/editor.html
  templates/systems/element_detail_tabs.html
Labels: bug

#1336 Oscal app inputs
  CHANGELOG.md
  controls/views.py
  guidedmodules/app_loading.py
  guidedmodules/app_source_connections.py
  guidedmodules/migrations/0053_auto_20210122_1502.py
  guidedmodules/models.py
  siteapp/views.py
Labels: CaC feature, enhancement, priority

#1331 Add task get_answer method to get a project task answer
  .pyup.yml
  CHANGELOG.md
  guidedmodules/models.py
  install-govready-q.sh
  q-files/vendors/govready/govready-q-files-startpack/q-files/lightweight-ato/app.yaml
  q-files/vendors/govready/govready-q-files-startpack/q-files/lightweight-ato/fisma_level.yaml
  q-files/vendors/govready/govready-q-files-startpack/q-files/lightweight-ato/templates/cp_printable.md
  q-files/vendors/govready/govready-q-files-startpack/q-files/lightweight-ato/templates/ssp_v1.md
  siteapp/tests.py
Labels: GRC feature

#1332 Feature/v0.9.1.50.1
  CHANGELOG.md
  VERSION
  controls/admin.py
  controls/forms.py
  controls/migrations/0037_deployment.py
  controls/migrations/0038_auto_20210114_1125.py
  controls/migrations/0039_auto_20210116_0026.py
  controls/migrations/0040_auto_20210117_0026.py
  controls/models.py
  controls/tests.py
  controls/urls.py
  controls/views.py
  siteapp/forms.py
  siteapp/tests.py
  siteapp/views.py
  system_settings/models.py
  templates/project.html
  templates/project_settings.html
  templates/systems/deployment_form.html
  templates/systems/deployment_history.html
  templates/systems/deployment_inventory.html
  templates/systems/deployments_list.html
  templates/task-finished.html
Labels: GRC feature

#1330 add smts on import record
  controls/views.py
Labels: CaC feature, GRC feature
