Repository GovReady/govready-q, pull requests merged in 2021-02, with the labels that each got.

#1368 Component library improvements
  CHANGELOG.md
  controls/migrations/0041_auto_20210203_0937.py
  controls/models.py
  controls/tests.py
  controls/views.py
  local-examples/local-ubuntu-postgres-nginx-gunicorn-supervisor-http/gunicorn.conf.py
  siteapp/static/css/govready-q.css
  siteapp/views.py
  system_settings/migrations/0005_delete_20210203_0506.py
  templates/components/component_library.html
  templates/components/element_detail_tabs.html
  templates/controls/editor.html
  templates/systems/components_selected.html
  templates/systems/element_detail_tabs.html
Labels: CaC feature, enhancement

#1325 Handle renaming the file based on the number of copies when making component copies
  controls/views.py
Labels: GRC feature

#1307 Handle Name Collisions when Editing a Component Name
  controls/views.py
  templates/components/element_detail_tabs.html
  templates/edit-component-modal.html
Labels: CaC feature

#1373 Require permissions on statement history
  CHANGELOG.md
  controls/views.py
Labels: CaC feature, security
